home_project_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('interface.urls')),
    path('p/', include('project.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('allauth/', include('allauth.urls')),
    path('auth/', include('auth_account.urls')),
]

SITE_ID = 1

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<uuid:id_>', views.ProjectView.as_view(), name='project'),
    path('<uuid:id_>/a/add', views.CreateActionItem.as_view(), name='action-item-add'),
    path('<uuid:id_>/m/add', views.AddMaterialView.as_view(), name='materials-add'),
]

project/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse

from data.models import Images, Properties, PropertySpaces
from .utils import money_fmt

property_ = property

status_choices = (
    ('pl', 'Planning'),
    ('ns', 'Not Started'),
    ('ip', 'In Progress'),
    ('cm', 'Completed'),
    ('hl', 'On Hold'),
)


# Create your models here.
class ProjectActionItem(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=40)
    description = models.TextField(null=True, blank=True)
    start_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    status = models.CharField(choices=status_choices, max_length=2, default='pl')
    images = models.ManyToManyField(Images, blank=True)


class Projects(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    property = models.ForeignKey(Properties, null=False, on_delete=models.CASCADE)
    property_space = models.ForeignKey(PropertySpaces, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=140)
    description = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    status = models.CharField(choices=status_choices, max_length=2, default='pl')
    cost = models.DecimalField(max_digits=19, decimal_places=2, null=True, blank=True)
    images = models.ManyToManyField(Images, blank=True)
    shared_users = models.ManyToManyField(User, blank=True)
    action_items = models.ManyToManyField(ProjectActionItem, blank=True)

    class Meta:
        unique_together = ['property', 'property_space', 'name']

    @property_
    def display_cost(self):
        return f"${self.cost:,}"

    @property_
    def url(self):
        return reverse('project', args=[self.id])

    def __str__(self):
        if self.property_space:
            return f"{self.property.name} - {self.property_space.name} - {self.name} ({self.id})"
        else:
            return f"{self.property.name} - Home - {self.name} ({self.id})"


class ProjectAttachments(models.Model):
    CHOICES = (
        ('db', 'DropBox'),
        ('od', 'OneDrive'),
        ('sp', 'SharePoint'),
        ('gd', 'GoogleDrive'),
        ('wa', 'URL'),
        ('im', 'Image'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    name = models.CharField(max_length=140)
    description = models.TextField(blank=True, null=True)
    type = models.CharField(max_length=2, choices=CHOICES)
    images = models.ManyToManyField(Images, blank=True)
    url = models.URLField(blank=True, null=True)


class ProjectMaterial(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=500, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    quantity = models.DecimalField(max_digits=10, decimal_places=4, null=True, blank=True)
    cost = models.DecimalField(max_digits=12, decimal_places=4, null=True, blank=True)

    @property_
    def display_cost(self):
        return money_fmt(self.cost, places=4, curr='$')

    @property_
    def display_total_cost(self):
        return money_fmt(self.cost * self.quantity, places=4, curr='$')

    @property_
    def total_cost(self):
        return self.cost * self.quantity

project/forms.py
from django import forms

from project import models


class AddMaterialForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['url'].widget.attrs.update({'class': 'form-control'})
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control',
                                                        'rows': 3})
        self.fields['quantity'].widget.attrs.update({'class': 'form-control'})
        self.fields['cost'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = models.ProjectMaterial
        fields = ['url', 'name', 'description', 'quantity', 'cost']

project/views.py
import logging
import uuid

import django.db.utils
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.views import View

from interface import create_forms
from .forms import AddMaterialForm
from . import models
from home_project_manager import utils
import project.utils as project_utils


class ProjectView(LoginRequiredMixin, View):
    template = "project.html"
    project = None
    context = {}

    def get(self, request, id_, material_form=AddMaterialForm):
        self.project = utils.get_project(id_)
        form = create_forms.CreateProjectsForm(instance=self.project)
        material_list = self.project.projectmaterial_set.all()
        # total_material_cost = self.project.projectmaterial_set.aggregate(Sum('total_cost'))

        self.context.update({'project': self.project,
                             'material_form': material_form,
                             'material_list': material_list,
                             'form': form,
                             'back_url': project_utils.get_project_parent_url(self.project)})

        utils.check_access(request, self.project.property)

        return render(request, template_name=self.template, context=self.context)


class CreateActionItem(LoginRequiredMixin, View):
    template = 'project_action_item_add.html'
    context = {}

    def get(self, request, id_):
        form = create_forms.CreateActionItemForm()
        self.context.update({'form': form,
                             'project': utils.get_project(id_)})

        return render(request, template_name=self.template, context=self.context)

    def post(self, request, id_):
        form = create_forms.CreateActionItemForm(request.POST)
        if form.is_valid():
            project = utils.get_project(id_)
            new_action_item = form.save()
            project.action_items.add(new_action_item)
            project.save()

            return HttpResponseRedirect(reverse('project', args=[id_]))

        self.context.update({'form': form})
        return render(request, template_name=self.template, context=self.context)


class AddMaterialView(LoginRequiredMixin, View):
    def post(self, request, id_):
        form = AddMaterialForm(request.POST)
        if form.is_valid():
            form.instance.project = utils.get_project(id)
            form.save()

            return HttpResponseRedirect(reverse('project', args=[id_]))
        else:
            return ProjectView.get(request, id_, form)

project/templates/project.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ project.name }}{% endblock %}

{% block head %}
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/materials-modal.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="d-flex mb-4 align-items-center">
            <div class="p-2">
                <a href="{{ back_url }}" class="btn btn-outline-primary bi bi-chevron-left" style="font-size: 2em;"
                aria-label="Click to go back to ''"></a>
{#                TODO: Finish label#}
            </div>
            <div class="p-2">
                <h1 class="display-3">{{ project.name }}</h1>
            </div>
            <div class="p-2 ms-auto">
                <a href="#" class="btn btn-outline-secondary"><i class="bi bi-pencil-square"></i></a>
            </div>
        </div>
        <div class="row p-3 bg-light rounded-3 mb-3">
            <div class="row">
                <div class="col">
                    <p>Start date: {{ project.start_date }}</p>
                </div>
                <div class="col">
                    <p>End Date: {{ project.end_date }}</p>
                </div>
                <div class="col">
                    <p>Status: {{ project.status }}</p>
                </div>
                <div class="col">
                    <p>Estimated Cost: {{ project.cost }}</p>
                </div>
            </div>
        </div>
        <div class="row py-4 px-3 bg-light rounded-3 mb-4">
            <div class="col">
                <p>Pictures: </p>
                <a href="#" class="btn btn-primary">Add an image</a>
            </div>
            <div class="col">
                <p>Documents: </p>
                <a href="#" class="btn btn-primary">Add a document</a>
            </div>
        </div>
        <ul class="nav nav-tabs mb-4" id="project-tabs" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="action-items-tab" data-bs-toggle="tab"
                        data-bs-target="#action-items" type="button" role="tab" aria-controls="action-items"
                        aria-selected="true">
                    Action Items
                </button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="materials-tab" data-bs-toggle="tab" data-bs-target="#materials"
                        type="button" role="tab" aria-controls="materials" aria-selected="false">
                    Materials
                </button>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="action-items" role="tabpanel" aria-labelledby="action-items-tab">
                <div class="py-4">
                    {% if not project.action_items %}
                        <div class="row">
                            <a href="{% url 'action-item-add' project.id %}" class="btn btn-primary">Add an action
                                item</a>
                        </div>
                    {% else %}
                        <div class="list-group mb-3">
                            {% for action_item in project.action_items.all %}
                                <button type="button" class="list-group-item list-group-item-action d-flex gap-3 py-3"
                                        data-bs-toggle="modal" data-bs-target="#_{{ action_item.id }}">
                                    <i class="bi bi-list"></i>
                                    <div class="col">{{ action_item.title }}</div>
                                    <div class="col">{{ action_item.description }}</div>
                                </button>
                                {% include 'components/modal_action_item.html' %}
                            {% endfor %}
                        </div>
                        <div class="row">
                            <div class="col-4"></div>
                            <div class="col-4">
                                <a href="{% url 'action-item-add' project.id %}" class="btn btn-primary">Add an action
                                    item</a>
                            </div>
                            <div class="col-4"></div>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="tab-pane" id="materials" role="tabpanel" aria-labelledby="materials-tab">
                <div class="py-4">
                    {% include 'components/project_materials.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project/templates/project_action_item_add.html
{% extends 'base.html' %}

{% block title %}Action Item{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="display-3 mb-4">Add an action item</h1>
        <form action="{% url 'action-item-add' project.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

project/templates/project_create.html
{% extends 'base.html' %}

{% block title %}Add a project{% endblock %}

{% block content %}
    <div class="container">
        <div class="d-flex mb-4 align-items-center">
            <div class="p-2">
                <a class="display-4" href="{{ parent.url }}">{{ parent.name }}</a>
            </div>
            <div class="p-2">
                <i class="display-4 bi bi-chevron-right"></i>
            </div>
            <div class="p-2">
                <h1 class="display-3">Add a project</h1>
            </div>
        </div>
        {% if project_already_exists %}
            <div class="alert alert-danger" role="alert">
                A project with this name already exists!
            </div>
        {% endif %}
        <form action="#" method="post" class="for">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_name" class="form-label">Project Name</label>
                {{ form.name }}
            </div>
            <div class="mb-3">
                <label for="id_description" class="form-label">Description</label>
                {{ form.description }}
            </div>
            <div class="row g-3 mb-3">
                <div class="col">
                    <label for="id_start_date" class="form-label">Start date</label>
                    {{ form.start_date }}
                </div>
                <div class="col">
                    <label for="id_end_date" class="form-label">End date</label>
                    {{ form.end_date }}
                </div>
            </div>
            <div class="mb-3">
                <label for="id_status" class="form-label">Status</label>
                {{ form.status }}
            </div>
            <div class="mb-3">
                <label for="id_cost" class="form-label">Estimated Cost</label>
                {{ form.cost }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}