home_project_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('interface.urls')),
    path('p/', include('project.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('allauth/', include('allauth.urls')),
    path('auth/', include('auth_account.urls')),
]

SITE_ID = 1

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<uuid:id_>', views.ProjectView.as_view(), name='project'),
    path('<uuid:id_>/a/add', views.CreateActionItem.as_view(), name='action-item-add'),
    path('<uuid:id_>/m/add', views.AddMaterialView.as_view(), name='materials-add'),
]

project/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse

from data.models import Images, Properties, PropertySpaces
from .utils import money_fmt

property_ = property

status_choices = (
    ('pl', 'Planning'),
    ('ns', 'Not Started'),
    ('ip', 'In Progress'),
    ('cm', 'Completed'),
    ('hl', 'On Hold'),
)


# Create your models here.
class ProjectActionItem(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=40)
    description = models.TextField(null=True, blank=True)
    start_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    status = models.CharField(choices=status_choices, max_length=2, default='pl')
    images = models.ManyToManyField(Images, blank=True)


class Projects(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    property = models.ForeignKey(Properties, null=False, on_delete=models.CASCADE)
    property_space = models.ForeignKey(PropertySpaces, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=140)
    description = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    status = models.CharField(choices=status_choices, max_length=2, default='pl')
    cost = models.DecimalField(max_digits=19, decimal_places=2, null=True, blank=True)
    images = models.ManyToManyField(Images, blank=True)
    shared_users = models.ManyToManyField(User, blank=True)
    action_items = models.ManyToManyField(ProjectActionItem, blank=True)

    class Meta:
        unique_together = ['property', 'property_space', 'name']

    @property_
    def display_cost(self):
        return f"${self.cost:,}"

    @property_
    def url(self):
        return reverse('project', args=[self.id])

    def __str__(self):
        if self.property_space:
            return f"{self.property.name} - {self.property_space.name} - {self.name} ({self.id})"
        else:
            return f"{self.property.name} - Home - {self.name} ({self.id})"


class ProjectAttachments(models.Model):
    CHOICES = (
        ('db', 'DropBox'),
        ('od', 'OneDrive'),
        ('sp', 'SharePoint'),
        ('gd', 'GoogleDrive'),
        ('wa', 'URL'),
        ('im', 'Image'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    name = models.CharField(max_length=140)
    description = models.TextField(blank=True, null=True)
    type = models.CharField(max_length=2, choices=CHOICES)
    images = models.ManyToManyField(Images, blank=True)
    url = models.URLField(blank=True, null=True)


class ProjectMaterial(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=500, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    quantity = models.DecimalField(max_digits=10, decimal_places=4, null=True, blank=True)
    cost = models.DecimalField(max_digits=12, decimal_places=4, null=True, blank=True)

    @property_
    def display_cost(self):
        return money_fmt(self.cost, places=4, curr='$')

    @property_
    def display_total_cost(self):
        return money_fmt(self.cost * self.quantity, places=4, curr='$')

    @property_
    def total_cost(self):
        return self.cost * self.quantity

project/forms.py
from django import forms

from project import models


class AddMaterialForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['url'].widget.attrs.update({'class': 'form-control'})
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control',
                                                        'rows': 3})
        self.fields['quantity'].widget.attrs.update({'class': 'form-control'})
        self.fields['cost'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = models.ProjectMaterial
        fields = ['url', 'name', 'description', 'quantity', 'cost']

project/views.py
import logging
import uuid

import django.db.utils
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.views import View

from interface import create_forms
from .forms import AddMaterialForm
from . import models
from home_project_manager import utils
import project.utils as project_utils


class ProjectView(LoginRequiredMixin, View):
    template = "project.html"
    project = None
    context = {}

    def get(self, request, id_, material_form=AddMaterialForm):
        self.project = utils.get_project(id_)
        form = create_forms.CreateProjectsForm(instance=self.project)
        material_list = self.project.projectmaterial_set.all()
        # total_material_cost = self.project.projectmaterial_set.aggregate(Sum('total_cost'))

        self.context.update({'project': self.project,
                             'material_form': material_form,
                             'material_list': material_list,
                             'form': form,
                             'back_url': project_utils.get_project_parent_url(self.project)})

        utils.check_access(request, self.project.property)

        return render(request, template_name=self.template, context=self.context)


class CreateActionItem(LoginRequiredMixin, View):
    template = 'project_action_item_add.html'
    context = {}

    def get(self, request, id_):
        form = create_forms.CreateActionItemForm()
        self.context.update({'form': form,
                             'project': utils.get_project(id_)})

        return render(request, template_name=self.template, context=self.context)

    def post(self, request, id_):
        form = create_forms.CreateActionItemForm(request.POST)
        if form.is_valid():
            project = utils.get_project(id_)
            new_action_item = form.save()
            project.action_items.add(new_action_item)
            project.save()

            return HttpResponseRedirect(reverse('project', args=[id_]))

        self.context.update({'form': form})
        return render(request, template_name=self.template, context=self.context)


class AddMaterialView(LoginRequiredMixin, View):
    def post(self, request, id_):
        form = AddMaterialForm(request.POST)
        if form.is_valid():
            form.instance.project = utils.get_project(id)
            form.save()

            return HttpResponseRedirect(reverse('project', args=[id_]))
        else:
            return ProjectView.get(request, id_, form)

project/templates/components/modal_action_item.html
<div id="_{{ action_item.id }}" class="modal fade" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title display-5">{{ action_item.title }}</h1>
                <div class="p-4">
                    <a href="#" class="btn btn-outline-secondary"><i class="bi bi-pencil-square"></i></a>
                </div>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Description</p>
                <textarea class="form-control" readonly>{{ action_item.description }}</textarea>
                <p>Start Date</p>
                <p>{{ action_item.start_date }}</p>
                <p>{{ action_item.end_date }}</p>
                <p>Status</p>
                <input type="radio" readonly>{{ action_item.status }}</input>
                <p>Images</p>
                <input type="file" readonly>{{ action_item.images }}</input>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

project/templates/components/project-materials.html
<div class="list-group mb-3">
    {% for material in material_list %}
        <button type="button" class="list-group-item list-group-item-action d-flex gap-3 py-3" data-bs-toggle="modal"
                data-bs-target="#materials-view-modal"
                data-bs-name="{{ material.name }}"
                data-bs-description="{{ material.description }}"
                data-bs-cost="{{ material.cost }}"
                data-bs-quantity="{{ material.quantity }}"
                data-bs-total-cost="{{ material.total_cost }}">
            <i class="bi bi-list"></i>
            <div class="col">{{ material.name }}</div>
            <div class="col">{{ material.description }}</div>
            <div class="col">{{ material.total_cost }}</div>
        </button>
    {% endfor %}
</div>
<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#materials-add-modal">Add materials</button>
<div class="modal fade" id="materials-add-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add materials</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'materials-add' project.id %}" method="POST">
                    {% csrf_token %}
                    <label for="id_url" class="form-label">Load from a URL</label>
                    <div class="input-group mb-3">
                        {{ material_form.url }}
                        <button class="btn btn-outline-secondary" type="button" id="url-button">Load</button>
                    </div>
                    <p style="text-align: center;">OR</p>
                    <div class="mb-2">
                        <label for="id_name" class="form-label">Name</label>
                        {{ material_form.name }}
                    </div>
                    <div class="mb-2">
                        <label for="id_description" class="form-label">Description</label>
                        {{ material_form.description }}
                    </div>
                    <div class="row mb-2">
                        <div class="col">
                            <label for="id_cost" class="form-label">Cost</label>
                            {{ material_form.cost }}
                        </div>
                        <div class="col">
                            <label for="id_quantity" class="form-label">Quantity</label>
                            {{ material_form.quantity }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="materials-view-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title display-6"></h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-4">
                        Name:
                    </div>
                    <div class="col" id="modal-material-name">
                        Placeholder
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        Description:
                    </div>
                    <div class="col" id="modal-material-description">
                        Placeholder
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        Cost:
                    </div>
                    <div class="col" id="modal-material-cost">
                        Placeholder
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        Quantity:
                    </div>
                    <div class="col" id="modal-material-quantity">
                        Placeholder
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

project/templates/components/project_materials.html
<div class="list-group mb-3">
    {% for material in material_list %}
        <button type="button" class="list-group-item list-group-item-action d-flex gap-3 py-3" data-bs-toggle="modal"
                data-bs-target="#materials-view-modal"
                data-bs-name="{{ material.name }}"
                data-bs-description="{{ material.description }}"
                data-bs-cost="{{ material.display_cost }}"
                data-bs-quantity="{{ material.quantity }}"
                data-bs-total-cost="{{ material.total_cost }}">
            <i class="bi bi-list"></i>
            <div class="col">{{ material.name }}</div>
            <div class="col">{{ material.total_cost }}</div>
        </button>
    {% endfor %}
</div>
<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#materials-add-modal">Add materials</button>
<div class="modal fade" id="materials-add-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add materials</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'materials-add' project.id %}" method="POST">
                    {% csrf_token %}
                    <label for="id_url" class="form-label">Load from a URL</label>
                    <div class="input-group mb-3">
                        {{ material_form.url }}
                        <button class="btn btn-outline-secondary" type="button" id="url-button">Load</button>
                    </div>
                    <p style="text-align: center;">OR</p>
                    <div class="mb-2">
                        <label for="id_name" class="form-label">Name</label>
                        {{ material_form.name }}
                    </div>
                    <div class="mb-2">
                        <label for="id_description" class="form-label">Description</label>
                        {{ material_form.description }}
                    </div>
                    <div class="row mb-2">
                        <div class="col">
                            <label for="id_cost" class="form-label">Cost</label>
                            {{ material_form.cost }}
                        </div>
                        <div class="col">
                            <label for="id_quantity" class="form-label">Quantity</label>
                            {{ material_form.quantity }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="materials-view-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title display-6"></h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-4">
                        Name:
                    </div>
                    <div class="col" id="modal-material-name">
                        Placeholder
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        Description:
                    </div>
                    <div class="col" id="modal-material-description">
                        Placeholder
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        Cost:
                    </div>
                    <div class="col" id="modal-material-cost">
                        Placeholder
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        Quantity:
                    </div>
                    <div class="col" id="modal-material-quantity">
                        Placeholder
                    </div>
                </div>
                <div class="row">
                    <br>
                </div>
                <div class="row">
                    <div class="col-4">
                        Total Cost:
                    </div>
                    <div class="col" id="modal-material-total-cost">
                        Placeholder
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>